# Site settings
title: PlantSat
email: spel@ing.uchile.cl
url: https://spel-uchile.github.io/plantasat
baseurl:
description: "Growing in space simulating Mars conditions"
keywords: "cubesat, nanosatellite, satellite, mars, plant, space"
skills: "Growing a plant in space simulating Mars conditions"
meta_author: University of Chile, GomSpace, RocketLabs


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: 

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: University of Chile
  location:
  social: Contact us!
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/SPEL_UCHILE
  - title: envelope
    url: mailto:spel@ing.uchile.cl
  - title: github
    url: http://github.com/spel-uchile

# Postal address (add as many lines as necessary)
address:
  - line: #Beauchef 850.
  - line: #Santiago, RM, Chile.

# Credits content
credits: #'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
#plugins:
#  - jekyll-twitter-plugin

collaborate:
  - name: University of Chile
    logo: uchile.png
    site: http://ingenieria.uchile.cl/english
  - name: D-Orbit
    logo: Dorbit-logo.png
    site: https://www.dorbit.space/
  - name: Gomspace
    logo: gomspace.png
    site: https://gomspace.com/home.aspx
